camunda.bpm.admin-user:
  id: demo
  password: demo
camunda:
  bpm:
    database:
      schema-update: 'true'
#      table-prefix: camunda.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heidy?nullCatalogMeansCurrent=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create-drop
      show-sql: 'true'
logging:
  level:
    org:
      camunda: DEBUG
  
      
