#H2 Database
spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
    show-sql: 'true'
      
camunda.bpm.admin-user:
  id: demo
  password: demo
  
camunda:
  bpm:
    database:
      type: h2
      schema-update: 'true'
      
      
      
      
#      table-prefix: camunda.
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/heidy
#    username: root
#    password: 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 5
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#      ddl-auto: create-drop
#      show-sql: 'true'
#logging:
#  level:
#    org:
#      camunda: DEBUG